version: '3'
volumes:
  db_data:
services:
  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: host.docker.internal
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: 
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql